rubric:
  pain:
    weight: 8
    description: Problem acuity
  roi:
    weight: 8
    description: Quantifiable value
  autoFit:
    weight: 8
    description: Agent solvability
  distribution:
    weight: 7
    description: Can Cobi reach buyers?
  defensibility:
    weight: 6
    description: Hard to replicate?
  speed:
    weight: 8
    description: Buildable in 7 days?
thresholds:
  alert: 40
  asset: 35
  content: 30
  research: 25
  log: 0
